const menuData = [
  {
    id: "momos",
    name: "Momos",
    items: [
      { name: "Veg Steamed Momo (8 pcs)", price: 159, veg: true },
      { name: "Chicken Steamed Momo (8 pcs)", price: 179, veg: false },
      { name: "Veg Tandoori Momo (8 pcs)", price: 189, veg: true },
      { name: "Chicken Tandoori Momo (8 pcs)", price: 229, veg: false },
    ],
  },
  {
    id: "soup",
    name: "Soup",
    items: [
      { name: "Hot & Sour Soup (Veg)", price: 149, veg: true },
      { name: "Chicken Hot & Sour Soup", price: 169, veg: false },
      { name: "Veg Manchow Soup", price: 149, veg: true },
      { name: "Chicken Manchow Soup", price: 169, veg: false },
    ],
  },
  {
    id: "starters-chinese-veg",
    name: "Starters Chinese (Veg)",
    items: [
      { name: "French Fry", price: 129, veg: true },
      { name: "Honey Chilli Potato", price: 209, veg: true },
      { name: "Chilli Potato", price: 199, veg: true },
      { name: "Chilli Paneer Dry", price: 289, veg: true },
      { name: "Chilli Mushroom Dry", price: 289, veg: true },
      { name: "Crispy Chilli Baby Corn", price: 289, veg: true },
    ],
  },
  {
    id: "starters-chinese-nonveg",
    name: "Starters Chinese (Non-Veg)",
    items: [
      { name: "Chilli Chicken Dry Boneless (8 pcs)", price: 309, veg: false },
      { name: "Chicken Loli Pop", price: 209, veg: false },
      { name: "Drums of Heaven (8 pcs)", price: 319, veg: false },
      { name: "Velox Special Chicken", price: 369, veg: false },
      { name: "Chef Special Chicken", price: 419, veg: false },
      { name: "Chilli Fish Dry (8 pcs Boneless)", price: 579, veg: false },
      { name: "Chilli Prawn Dry", price: 599, veg: false },
    ],
  },
  {
    id: "rice-noodle",
    name: "Rice &amp; Noodle",
    items: [
      { name: "Veg Fried Rice", price: 189, veg: true },
      { name: "Veg Chilli Garlic Fried Rice", price: 229, veg: true },
      { name: "Chicken Fried Rice", price: 239, veg: false },
      { name: "Chilli Garlic Fried Rice Chicken", price: 269, veg: false },
      { name: "Mix Fried Rice", price: 319, veg: false },
      { name: "Egg Fried Rice", price: 219, veg: false },
      { name: "Veg Hakka Noodle", price: 219, veg: true },
      { name: "Egg Hakka Noodle", price: 219, veg: false },
      { name: "Chicken Hakka Noodle", price: 239, veg: false },
      { name: "Mix Hakka Noodle", price: 319, veg: false },
      { name: "Veg Chilli Garlic Noodle", price: 239, veg: true },
      { name: "Chicken Chilli Garlic Noodle", price: 259, veg: false },
    ],
  },
  {
    id: "chinese-main-course-veg",
    name: "Chinese Main Course (Veg)",
    items: [
      { name: "Chilli Paneer Gravy", price: 269, veg: true },
      { name: "Chilli Mushroom Gravy", price: 269, veg: true },
      { name: "Veg Manchurian Gravy", price: 269, veg: true },
    ],
  },
  {
    id: "chinese-main-course-nonveg",
    name: "Chinese Main Course (Non-Veg)",
    items: [
      { name: "Chilly Chicken Gravy Boneless (8 pcs)", price: 339, veg: false },
      { name: "Chicken Manchurian Gravy", price: 339, veg: false },
      { name: "Chilly Fish Gravy Boneless (8 pcs)", price: 639, veg: false },
      { name: "Chilly Prawn Gravy (6 pcs)", price: 639, veg: false },
    ],
  },
  {
    id: "biryani",
    name: "Biryani",
    items: [
      { name: "Special Handi Veg Biryani", price: 259, veg: true },
      { name: "Special Handi Biryani Chicken (4 pcs)", price: 369, veg: false },
      { name: "Special Handi Biryani Mutton (3 pcs)", price: 469, veg: false },
      { name: "Chicken Kachi Biryani (2 pcs)", price: 289, veg: false },
      { name: "Mutton Kachi Biryani (2 pcs)", price: 349, veg: false },
    ],
  },
  {
    id: "arabian-mandi",
    name: "Arabian Mandi",
    items: [
      { name: "Murg Faham Mandi", price: 1199, veg: false },
      { name: "Arabian Madfoon Mandi Raan", price: 2499, veg: false },
    ],
  },
  {
    id: "indian-main-course-veg",
    name: "Indian Main Course (Veg)",
    items: [
      { name: "Yellow Dal Fry", price: 229, veg: true },
      { name: "Dal Makhani", price: 249, veg: true },
      { name: "Dhaba Dal", price: 259, veg: true },
      { name: "Mix Veg", price: 239, veg: true },
      { name: "Shahi Paneer", price: 289, veg: true },
      { name: "Mutter Paneer", price: 289, veg: true },
      { name: "Paneer Butter Masala", price: 289, veg: true },
      { name: "Paneer Tikka Lababder", price: 339, veg: true },
      { name: "Kadhai Paneer", price: 269, veg: true },
      { name: "Mushroom Masala", price: 259, veg: true },
    ],
  },
  {
    id: "indian-main-course-nonveg",
    name: "Indian Main Course (Non-Veg)",
    items: [
      { name: "Egg Curry (2 pcs)", price: 189, veg: false },
      { name: "Chicken Curry (4 pcs)", price: 299, veg: false },
      { name: "Chicken Tikka Lababder (6 pcs Boneless)", price: 349, veg: false },
      { name: "Kadhai Chicken (4 pcs With Bone)", price: 349, veg: false },
      { name: "Tandoori Butter Chicken (Half)", price: 399, veg: false },
      { name: "Tandoori Butter Chicken (Full)", price: 669, veg: false },
      { name: "Chicken Lahori (6 pcs Boneless)", price: 349, veg: false },
      { name: "Murgh Changezi (Half)", price: 399, veg: false },
      { name: "Murgh Changezi (Full)", price: 669, veg: false },
      { name: "Murg Kali Mirch (4 pcs)", price: 329, veg: false },
      { name: "Mutton Rogan Josh (3 pcs)", price: 399, veg: false },
      { name: "Bhuna Mutton (3 pcs)", price: 399, veg: false },
      { name: "Mutton Korma (3 pcs)", price: 399, veg: false },
      { name: "Mutton Nihari (3 pcs)", price: 399, veg: false },
      { name: "Mutton Adraki Panje Masala (2 pcs)", price: 429, veg: false },
      { name: "Mutton Lal Mass (3 pcs)", price: 429, veg: false },
      { name: "Tabak Mass (4 pcs)", price: 469, veg: false },
      { name: "Champaran Mutton Handi (8 pcs)", price: 1099, veg: false },
    ],
  },
  {
    id: "tandoori-starters-veg",
    name: "Tandoori Starters (Veg)",
    items: [
      { name: "Paneer Tikka (6 pcs)", price: 269, veg: true },
      { name: "Lazeez Paneer Tikka (6 pcs)", price: 269, veg: true },
      { name: "Paneer 65 (6 pcs)", price: 269, veg: true },
    ],
  },
  {
    id: "tandoori-starters-nonveg",
    name: "Tandoori Starters (Non-Veg)",
    items: [
      { name: "Murg Mughlai Shikanj", price: 609, veg: false },
      { name: "Tandoori Chicken (Half)", price: 299, veg: false },
      { name: "Tandoori Chicken (Full)", price: 589, veg: false },
      { name: "Angara Tandoori Chicken (Half)", price: 309, veg: false },
      { name: "Angara Tandoori Chicken (Full)", price: 589, veg: false },
      { name: "Tandoori Afgani (Half)", price: 339, veg: false },
      { name: "Tandoori Afgani (Full)", price: 619, veg: false },
      { name: "Jugal Bandi Seek Kebab", price: 569, veg: false },
      { name: "Chicken Seekh Kebab (4 pcs)", price: 269, veg: false },
      { name: "Classic Chicken Tikka (6 pcs)", price: 269, veg: false },
      { name: "Hariyali Chicken Tikka (6 pcs)", price: 269, veg: false },
      { name: "Chicken Malai Tikka (6 pcs)", price: 269, veg: false },
      { name: "Mutton Adraki Panje (2 pcs)", price: 369, veg: false },
      { name: "Karachi Nalli Kabab (1 pc)", price: 349, veg: false },
      { name: "Mutton Seekh Kebab (4 pcs)", price: 399, veg: false },
      { name: "Mutton Chapli Kebab (2 pcs)", price: 439, veg: false },
      { name: "Mutton Sikandri Raan (1.5 kg)", price: 2199, veg: false },
      { name: "Tandoori Fish Tikka (6 pcs)", price: 599, veg: false },
      { name: "Sarsho Wali Fish Tikka (6 pcs)", price: 599, veg: false },
      { name: "Tandoori Prawn (8 pcs)", price: 639, veg: false },
      { name: "Prawn Fry", price: 639, veg: false },
      { name: "Tandoori Pomfret Fish (1 pc)", price: 569, veg: false },
      { name: "Pomfret Fry Fish (1 pc)", price: 569, veg: false },
      { name: "Chicken 65 (6 pcs)", price: 339, veg: false },
      { name: "Fish 65 (6 pcs)", price: 569, veg: false },
    ],
  },
  {
    id: "indian-breads",
    name: "Indian Breads",
    items: [
      { name: "Tandoori Roti", price: 25, veg: true },
      { name: "Tandoori Butter Roti", price: 30, veg: true },
      { name: "Khameri Roti", price: 35, veg: true },
      { name: "Plain Naan", price: 49, veg: true },
      { name: "Butter Naan", price: 59, veg: true },
      { name: "Garlic Naan", price: 79, veg: true },
      { name: "Cheese Garlic Naan", price: 119, veg: true },
      { name: "Laccha Paratha", price: 79, veg: true },
      { name: "Roomali Roti", price: 15, veg: true },
    ],
  },
  {
    id: "raita-salads",
    name: "Raita &amp; Salads",
    items: [
      { name: "Mix Raita", price: 99, veg: true },
      { name: "Plain Curd", price: 79, veg: true },
      { name: "Green Salad", price: 59, veg: true },
      { name: "Onion Yam Yam Salad", price: 29, veg: true },
      { name: "Plain Papad (1 pc)", price: 20, veg: true },
      { name: "Masala Papad (2 pcs)", price: 69, veg: true },
    ],
  },
  {
    id: "dessert",
    name: "Dessert",
    items: [
      { name: "Nolen Gur Ice Cream (125 ml)", price: 159, veg: true },
      { name: "Anjir Ice Cream (125 ml)", price: 159, veg: true },
      { name: "Paan Ice Cream (125 ml)", price: 159, veg: true },
      { name: "Doodh Dulari", price: 249, veg: true },
      { name: "Kunafa", price: 249, veg: true },
    ],
  },
  {
    id: "beverages",
    name: "Beverages",
    items: [
      { name: "Virgin Mint Mojito", price: 149, veg: true },
      { name: "Blue Lagun", price: 149, veg: true },
      { name: "Watermelon Mojito", price: 149, veg: true },
      { name: "Cucumber Mojito", price: 149, veg: true },
      { name: "Green Apple Mojito", price: 149, veg: true },
      { name: "Fresh Lime Soda", price: 79, veg: true },
      { name: "Oreo Shake", price: 169, veg: true },
      { name: "Cold Coffee", price: 169, veg: true },
      { name: "Cold Coffee with Ice Cream", price: 199, veg: true },
    ],
  },
  {
    id: "soft-drink",
    name: "Soft Drink",
    items: [
      { name: "Soft Drink (300 ml)", price: 80, veg: true },
      { name: "Red Bull", price: 130, veg: true },
      { name: "Packaged Water", price: 30, veg: true },
    ],
  },
];
